export const TEACHER_LOGIN_REQUEST = 'TEACHER_LOGIN_REQUEST'
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS'
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL'
export const TEACHER_LOGOUT = 'TEACHER_LOGOUT'